export interface EstabelecimentoDTO {
    idEstab?: number,
    responsavel?: number,
    status?: boolean,
    razao_social?: string,
    cnpj?: string,
    nome_fantasia?: string,
    email?: string,
    site?: string,
    tel_fixo?: string,
    tel_cel?: string,
    descr_negocio?: string,
    cep?: string,
    logradouro?: string,
    numero?: string,
    complemento?: string,
    bairro?: string,
    cidade?: string,
    estado?: string,
    horario_func?: string,
    foto_logomarca?: string,
    data_criacao?: Date,
    id_subcat?: number,
    id_servico?: number,
}